#
# Caches a set of credentials from Keeper to stop too many API calls
#
- name: Read Inventory File and find customer names
  ansible.builtin.command:
    cmd: "grep 'ksm_uid' ../inventories/Inventory.yml"
  register: log_uids

- name: Extract UIDs from Inventory
  ansible.builtin.debug:
    msg: "{{ log_uids.stdout_lines | replace('ksm_uid: ', '' ) | replace('  ', '') }}"
  register: uid_list

- name: Generate a Keeper Record Cache secret
  keepersecurity.keeper_secrets_manager.keeper_password:
    length: 64
  register: keeper_record_cache_secret
  no_log: True

- name: Store the Keeper Record Cache secret into variables.
  set_fact:
    keeper_record_cache_secret: "{{ keeper_record_cache_secret.password }}"
  no_log: True

- name: Cache records. Will use keeper_record_cache_secret from above.
  keepersecurity.keeper_secrets_manager.keeper_cache_records:
    uids: "{{ key_list.msg +  uid_list.msg }}"
  register: keeper_record_cache
  no_log: True

- name: Create Host Fact for cache
  ansible.builtin.set_fact:
    keeper_record_cache: "{{ keeper_record_cache.cache }}"
    cacheable: true
